os:
  - linux
  - osx
language: generic
env:
  - SWIFT_VERSION=swift-3.0-PREVIEW-4
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_BUILD=Ubuntu14
    - os: linux
      dist: wily
      sudo: required
      env: SWIFT_BUILD=Ubuntu15
    - os: osx
      osx_image: xcode8
      env: SWIFT_BUILD=OSX
install:
  - ./Travis/BeforeInstall.sh
script:
  - make dist
