os:
	- linux
	- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.0
env:
	- SWIFT_VERSION=swift-3.0-PREVIEW-6
install:
	- mkdir swift
	- curl https://swift.org/builds/swift-3.0-preview-6/ubuntu1404/swift-3.0-PREVIEW-6/swift-3.0-PREVIEW-6-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
script:
	- env PATH=$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH make
