
//
//  Constants.swift
//  IORunner
//
//  Created by ilker özcan on 04/07/16.
//  Auto generated by Makefile
//
//

public struct Constants {

	public static let APP_NAME = "IO Runner"
	public static let APP_VERSION = "1.0.0"
	public static let APP_VERSION_INT = "100"
	public static let APP_CREDITS = "Copyright (c) 2016 Ilker Özcan"
	public static let APP_PACKAGE_NAME = "IORunner"

	public static let CpuSleepMsec = 0.3
	public static let CpuSleepSec: UInt32 = 300000
	public static let GuiRefreshRate: UInt32 = 30000

}


